/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {

    // Apache Http Client
    api(libs.apache.http.client)

    // Gson
    api(libs.gson)

    // Testing
    testImplementation(libs.junit.jupiter.engine)

    testImplementation(libs.testcontainers)

    testImplementation(libs.testcontainers.junit.jupiter)

    testImplementation(libs.logback.classic)

}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
