# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Gradle Build

on:
  push:
    branches: [ 'main' , 'dev' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' , '11' , '17' , '21' ]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup JDK ${{ matrix.Java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 15

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

    - name: Build and Publish with Gradle to GitHub Packages
      run: ./gradlew build
      env:
        OSSRH_MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
        OSSRH_MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_SIGNING_KEY_ID: ${{ secrets.OSS_SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.OSS_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.OSS_SIGNING_PASSWORD }}
